# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Youtube' do
	use_frameworks!
  pod 'GoogleSignIn', '~> 5.0'

#  pod 'YouTubePlayer', '~> 0.4'

#  pod 'YouTubePlayer-Swift', '~> 1.0'

#  pod 'YoutubePlayerView', '~> 1.1'

   pod 'YoutubeKit'

   pod 'SVProgressHUD'

   pod 'moa', '~> 12.0'
end
